<a href="https://colab.research.google.com/github/amanda-araujo/applied-linear-algebra/blob/main/decomposicaoQR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decomposição QR

In [10]:
import numpy as np
np.set_printoptions(suppress=True)

**Problema**: dada uma matriz quadrada qualquer A, encontrar seus autovalores.

***Pontos importantes***:
*   Autovalores matriz triangular → diagonal principal
*   Matrizes similares: mesmos autovalores
*   Transformação de similaridade: $B = M^{-1}AM$, $M$ inversível
*   Matriz ortonormal: $Q^{-1} = Q^T$
*   Decomposição (ou fatoração) QR: dada qualquer matriz A $m×n$, temos: A = QR, onde Q ∈ $\mathbb{R}^{m×m}$ ortogonal e R ∈ $\mathbb{R}^{m×n}$ triangular superior.

**Ideia**: Transformar a matriz A de modo a ter uma matriz similar triangular, onde os autovalores são facilmente obtidos, sendo a diagonal principal da matriz.




In [22]:
# Matriz quadrada qualquer
A = np.vander(np.array([1, 2, 3, 4, 5])) # matriz de Vandermonde (termos de cada linha estão em progressão geométrica)
print(A)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Deseja-se transformar A em uma matriz triangular, mantendo seus autovalores.

* Os autovalores da matriz A pode ser conservados através de uma transformação de similaridade: $B = M^{-1}AM$, $M$ inversível.

Essa propriedade é útil se a matriz B similar for triangular. Vamos encontrar $M$ inversível tal que isso seja satisfeito.

> Uma matriz boa de se trabalhar e que é inversível é uma matriz ortonormal: $B = Q^{-1}AQ = Q^{T}AQ$. Uma matriz ortonormal Q pode ser obtida a partir da própria matriz A, utilizando a *decomposição QR*: $A = QR$

Desse modo, temos:
$B = Q^{T}AQ = Q^{T}(QR)Q = RQ$.
Logo, $B = RQ$


In [23]:
Q1, R1 = np.linalg.qr(A) # decomposição QR
B1 = Q1.T @ A @ Q1       # transformação de similaridade (mesmos autovalores)
print(B1)

[[  11.70370362   95.94985219 -391.83817342  548.76240376  141.99011309]
 [   3.74545605   11.42886867  -12.06749667   -4.41288385   -6.03073889]
 [  -1.60429851   -1.31349271   -0.19198933    0.15806735   -0.47209789]
 [   0.64226745    0.00069666    0.06699352    0.05543297   -0.06265891]
 [   0.0579779    -0.02211493   -0.00958549   -0.00507957    0.00398406]]


In [24]:
Q2, R2 = np.linalg.qr(B1) # decomposição QR
B2 = Q2.T @ B1 @ Q2       # transformação de similaridade (mesmos autovalores)
print(B2)

[[ 115.68622618  370.62194891 -452.21166965  270.56856131  -61.22404307]
 [ -31.7512938  -117.64692367  157.63938398 -102.58204324   25.34084046]
 [  -3.74105044  -15.14265967   26.48924234  -21.88724748    6.74361227]
 [  -0.09133312   -0.39278026    0.8289485    -1.569848      0.87873481]
 [  -0.00019546   -0.00088038    0.00212591   -0.00624528    0.04130314]]


Note que: os valores abaixo da diagonal principal estão se aproximando de zero.

**Ideia básica do procedimento**:

Seja $A_0 = A$
1.   Obtenha $A_0 = Q_0R_0$ (*decomposição QR* )
2.   Defina $A_1 = Q_0^TA_0Q_0$
3.   Obtenha $A_1 = Q_1R_1$ (*decomposição QR* )
4.   Defina $A_2 = Q_1^TA_1Q_1$
5.   Repita até... obter matriz aproximadamente triangular superior


In [25]:
def algoritmoQR(A, iter):

  B = A

  for i in range(iter):
    Q, R = np.linalg.qr(B)
    B = Q.T @ B @ Q

  return B

In [26]:
print(algoritmoQR(B2, 10))

[[  46.33822053  332.98633461 -514.68441635  307.66599019  -66.779145  ]
 [  -0.08541024  -29.32149386   63.50176862  -47.79952069   12.76351153]
 [  -0.00000001   -0.00000355    6.79539417   -9.37454125    3.58763849]
 [  -0.           -0.            0.           -0.84961949    0.64728609]
 [  -0.           -0.            0.           -0.            0.03749864]]


In [20]:
# Autovalores da matriz A
np.linalg.eigvals(A)

array([ 45.96043479, -28.94370187,   6.79538792,  -0.84961948,
         0.03749864])

Para melhorar, aumentar o número de iterações

In [27]:
print(algoritmoQR(B2, 20))

[[  45.96412364  333.07086454 -514.75546618  307.71949702  -66.79344218]
 [  -0.00082962  -28.94739072   62.92350346  -47.45384027   12.68847997]
 [  -0.           -0.            6.79538792   -9.37453655    3.58763723]
 [  -0.           -0.            0.           -0.84961948    0.64728609]
 [  -0.           -0.            0.           -0.            0.03749864]]


In [37]:
# Algoritmo QR
def QR_algoritmo(A, iter):

  B = A

  for i in range(iter):
    Q, R = np.linalg.qr(B)
    B = R @ Q

  return B

In [51]:
print(QR_algoritmo(A, 20))

[[  45.96973691  333.06960194 -514.75440564  307.71869722  -66.79322833]
 [  -0.00209222  -28.953004     62.93217873  -47.45902632   12.68960565]
 [  -0.           -0.            6.79538792   -9.37453655    3.58763723]
 [  -0.           -0.            0.           -0.84961948    0.64728609]
 [  -0.           -0.            0.           -0.            0.03749864]]


In [56]:
iter = 50
print('Autovalores da matriz A:')
print(np.linalg.eigvals(A))
print('Autovalores da matriz A via algoritmo QR (' + str(iter) + ' iterações):')
print(np.diag(QR_algoritmo(A, iter)))

Autovalores da matriz A:
[ 45.96043479 -28.94370187   6.79538792  -0.84961948   0.03749864]
Autovalores da matriz A via algoritmo QR (50 iterações):
[ 45.96043479 -28.94370188   6.79538792  -0.84961948   0.03749864]
